name: todo
description: An example todos app that showcases bloc state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  meta: ^1.11.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  uuid: ^3.0.7

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
